### ISSUE TITLE
脚本中ssr问题。

### ISSUE THREAD

**Issue by gaaraljh** [esirplayground/AutoBuild-OpenWrt#111]
esir大神，脚本文件中“sed -i '5s/#//' feeds.conf.default” ，是为了使用feeds.conf.default文件中的helloworld源，现在他的源位置改到11行了，应该改成：sed -i '11s/#//' feeds.conf.default“，不然ssr-plus就找不到源安装不了，不知道这么说对不对，我是这样才安装了ssr。

**Comment by esirplayground** [comment]
谢谢，已改
