### ISSUE TITLE
你好你的高大全版不支持wpa

### ISSUE THREAD

**Issue by guanzi008** [esirplayground/AutoBuild-OpenWrt#116]
Openwrt 无线 WPA/WPA2加密 及无线客户端模式WPA/WPA2 加密

Openwrt无线客户端 连接时如果只装Hostapd 做为AP模式 可以使用WPA2加密
如果做为客户端加密便需要 用到 wpa-supplicant 
 
 
编译环境
make menuconfig
按 / 后 搜索 找到位置并添加
 
hostapd  AP模式 WPA/WPA2支持
 
wpa-supplicant 无线客户端模式 WPA/WPA2 支持
 
 
 
 
或者刷好包联网后  SSL连接路由
opkg update ---更新软件列表

opkg install hostapd
opkg install wpa-supplicant
 

没有这个
我的软路由配无线网卡无法正常使用

**Comment by guanzi008** [comment]
大佬，什么时候更新一下你的高大全版啊。

**Comment by esirplayground** [comment]
就不赞成你们用网卡搞ap，就算搞成了，无线信号也是差的一匹，有啥必要折腾，买个wifi6的路由不香吗？

**Comment by guanzi008** [comment]
我竟无言以对，主要是因为手里有一个usb的无线网卡从同事电脑上拆下来的，原因是这个网卡插入同事电脑就蓝屏，所以打算拿去插在软路由里使用
