### ISSUE TITLE
10.1高大上版本有异常

### ISSUE THREAD

**Issue by BCYDTZ** [esirplayground/AutoBuild-OpenWrt#128]
最新的10.1版本中，在DHCP那边默认勾选了忽略解析文件，而9.1版本就没有勾选，勾选之后，导致不能正常上网
![IMG_20201008_082653](https://user-images.githubusercontent.com/72110372/95454576-3cd56480-099f-11eb-92b8-5532eba5d2d6.jpg)

**Comment by esirplayground** [comment]
选不选都不影响上网，如果你是保留配置升级。
固件问题请到群里询问，这里是脚本相关问题的讨论区
