### ISSUE TITLE
esir，要先删除再git clone的怎处理？

### ISSUE THREAD

**Issue by exLuLu** [esirplayground/AutoBuild-OpenWrt#195]
像这个主题 https://github.com/jerrykuku/luci-theme-argon/tree/18.06 ，要先rm -rf luci-theme-argon，再git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git，怎么处理？

我在Build_OP_x86_64.yml 里面添加了这段（在- name: Import external feeds 上面添加，而且码都按要求对齐了）
    - name: Install theme
      working-directory: ./openwrt
      run: |
        #也试过不加sudo
        sudo rm -rf package/lede/luci-theme-argon
        git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git package/luci-theme-argon

然后在x86_64.config 里面添加
CONFIG_PACKAGE_luci-theme-argon=y

最后出来的固件里面还是Lean源码里的argon主题，并非jerrykuku的版本

**Comment by esirplayground** [comment]
x86_64的 yaml file 和 customize.sh 改了一下，你参考一下吧

**Comment by exLuLu** [comment]
> x86_64的 yaml file 和 customize.sh 改了一下，你参考一下吧

谢谢e大！

**Comment by exLuLu** [comment]
e大能不能说一下工作原理？为什么在yml rm没起作用？

**Comment by esirplayground** [comment]
你指定错了目录，是lean，不是lede

**Comment by exLuLu** [comment]
> 你指定错了目录，是lean，不是lede

啊啊啊啊啊！！！这。。。。太TMSB了我
