### ISSUE TITLE
编译固件的时候能否设置网口

### ISSUE THREAD

**Issue by istraw** [esirplayground/AutoBuild-OpenWrt#197]
每次刷机后，原来的wan口变成lan口，都要重新插网线设置一遍。有没有办法在编译的时候脚本设置下eth0是wan口，其他口是lan口？谢谢大佬

**Comment by esirplayground** [comment]
不行，eth0是第一个网卡设备，
1. 如果设备只有一个网口，插网线就无法进行后台设置，直接断网；
2. 如果设备有多个网口，Lan对应在eth0上，就会被安排在把头的位置，这样方便初上手的人找到
