### ISSUE TITLE
建议添加r8168驱动

### ISSUE THREAD

**Issue by summyliang** [esirplayground/AutoBuild-OpenWrt#222]
目前用的小马v1，网卡是rtl8111，高大全版本默认使用的是r8169驱动，兼容性有点问题，有时会掉到百兆。网上看了一圈好像得单独编译，但必须首先完整编译一次固件才能单独编译ipk，似乎很麻烦……所以希望下个版本能增加rtl8111专属的r8168驱动，谢谢！

相关驱动在这里：https://github.com/goldkeyber112/openwrt-r8168

**Comment by esirplayground** [comment]
8169 和8168驱动冲突，只能二选一，如果需要8168，需要取消8169，但此举会影响其他兼容8169的网卡，你的意见？

**Comment by summyliang** [comment]
> 8169 和8168驱动冲突，只能二选一，如果需要8168，需要取消8169，但此举会影响其他兼容8169的网卡，你的意见？
感谢回复，之后又折腾了很久并且换了设备，发现我这个掉百兆问题似乎和驱动无关，所以还是保留r8169驱动吧不作任何改动，谢谢！
