### ISSUE TITLE
编译ac2100报错Errors were encountered while processing:  mysql-common E: Sub-process /usr/bin/dpkg returned an error code (1) Error: Process completed with exit code 100.

### ISSUE THREAD

**Issue by ASFLY61** [esirplayground/AutoBuild-OpenWrt#225]
通过push方法激活编译，编译到3-4min左右，报错信息如下
![报错](https://user-images.githubusercontent.com/31264679/146213452-6455b952-dd06-4ca9-8088-ff23f5164c0d.png)
Errors were encountered while processing:
 mysql-common
E: Sub-process /usr/bin/dpkg returned an error code (1)
Error: Process completed with exit code 100.

请教下大家如何解决

**Comment by wtf7788** [comment]
我也遇到了，不过我暂时的解决方案为将ubuntu的版本指定为ubuntu-18.04，可以编译

**Comment by ASFLY61** [comment]
> 我也遇到了，不过我暂时的解决方案为将ubuntu的版本指定为ubuntu-18.04，可以编译

感谢回复，改成18.04版本正常编译了
