### ISSUE TITLE
Build_OP_NanoPi_R4S.yml   报错

### ISSUE THREAD

**Issue by n0tsur3** [esirplayground/AutoBuild-OpenWrt#237]
**Rebuild OpenWrt To Collect Error Log If Failed**

Run cd "/home/runner/openwrt"

make[2]: Entering directory '/home/runner/openwrt/scripts/config'
cc -O2   -c -o conf.o conf.c
cc -O2   -c -o confdata.o confdata.c
cc -O2   -c -o expr.o expr.c
cc -O2 -I ./.   -c -o lexer.lex.o lexer.lex.c
cc -O2 -I ./.   -c -o parser.tab.o parser.tab.c
cc -O2   -c -o preprocess.o preprocess.c
cc -O2   -c -o symbol.o symbol.c
cc -O2   -c -o util.o util.c
cc   conf.o confdata.o expr.o lexer.lex.o parser.tab.o preprocess.o symbol.o util.o   -o conf
make[2]: Leaving directory '/home/runner/openwrt/scripts/config'
make[2]: Entering directory '/home/runner/openwrt'
make[3]: Entering directory '/home/runner/openwrt/scripts/config'
set -e; mkdir -p ./; trap "rm -f ./.mconf-cfg.tmp" EXIT; { /bin/sh mconf-cfg.sh; } > ./.mconf-cfg.tmp; if [ ! -r mconf-cfg ] || ! cmp -s mconf-cfg ./.mconf-cfg.tmp; then true '  UPD     mconf-cfg'; mv -f ./.mconf-cfg.tmp mconf-cfg; fi
cc -O2 -D_GNU_SOURCE -D_DEFAULT_SOURCE   -c -o mconf.o mconf.c
cc -O2 -D_GNU_SOURCE -D_DEFAULT_SOURCE   -c -o lxdialog/checklist.o lxdialog/checklist.c
cc -O2 -D_GNU_SOURCE -D_DEFAULT_SOURCE   -c -o lxdialog/inputbox.o lxdialog/inputbox.c
cc -O2 -D_GNU_SOURCE -D_DEFAULT_SOURCE   -c -o lxdialog/menubox.o lxdialog/menubox.c
cc -O2 -D_GNU_SOURCE -D_DEFAULT_SOURCE   -c -o lxdialog/textbox.o lxdialog/textbox.c
cc -O2 -D_GNU_SOURCE -D_DEFAULT_SOURCE   -c -o lxdialog/util.o lxdialog/util.c
cc -O2 -D_GNU_SOURCE -D_DEFAULT_SOURCE   -c -o lxdialog/yesno.o lxdialog/yesno.c
cc -o mconf mconf.o lxdialog/checklist.o lxdialog/inputbox.o lxdialog/menubox.o lxdialog/textbox.o lxdialog/util.o lxdialog/yesno.o confdata.o expr.o lexer.lex.o parser.tab.o preprocess.o symbol.o util.o -lncurses -ltinfo
make[3]: Leaving directory '/home/runner/openwrt/scripts/config'
make[3]: Entering directory '/home/runner/openwrt'
make[3]: Leaving directory '/home/runner/openwrt'
Error opening terminal: unknown.
make[2]: *** [menuconfig] Error 1
/home/runner/openwrt/include/toplevel.mk:133: recipe for target 'menuconfig' failed
make[2]: Leaving directory '/home/runner/openwrt'
make[1]: *** [.config] Error 2
/home/runner/openwrt/include/toplevel.mk:92: recipe for target '.config' failed
make: *** [world] Error 2
/home/runner/openwrt/include/toplevel.mk:228: recipe for target 'world' failed
Error: Process completed with exit code 2.

**Comment by canmy777** [comment]
同样，编译报错
<img width="659" alt="2022-1-30 0-18-20" src="https://user-images.githubusercontent.com/28658345/151668552-a92d51a6-5b02-4288-b940-c52c21342e6e.png">
<img width="655" alt="2022-1-30 0-18-44" src="https://user-images.githubusercontent.com/28658345/151668571-cbc96132-0280-426b-ab52-393b04d281db.png">

[logs_1.zip](https://github.com/esirplayground/AutoBuild-OpenWrt/files/7964093/logs_1.zip)

**Comment by linkq** [comment]
我这也一样

**Comment by esirplayground** [comment]
@Kurokosama
