### ISSUE TITLE
不好意思，问esir个问题哈

### ISSUE THREAD

**Issue by GreatMichaelLee** [esirplayground/AutoBuild-OpenWrt#254]
看来您那个给overlay扩容的视频，我的R4s用的外接优盘来扩容的，我发现弄完没问题啊，重启扩容的也还在，但是重新刷完固件（即便我选保留配置）之后这个设为外置的overlay的配置就掉了啊（具体表现为df -h看挂载点和大小，发现恢复回原来内置的overlay了），我尝试了一下，要把优盘上的那些/upper /work/之类全删除再重新拷贝一次，然后再重新挂载重启一次才能好啊，这个就有点烦了，我没几天都要刷一个新版本，这样弄的话，那我每次升级固件不得手工维护得烦死，有什么好办法吗@esirplayground

我初步怀疑是刷了固件之后原来在优盘上那些目录里的内容不知什么原因不同步了，或者不相容了，导致mount不上，需要重新同步内置overlay得内容后才能挂载，猜的，不知道是不是这样，因为重新拷贝一下内置overlay得内容后就能挂在上了。

**Comment by esirplayground** [comment]
没几天都要刷一个新版本，这样的话，就直接编译overlay大点的固件好了，不要折腾什么扩容了

**Comment by Doublefire-Chen** [comment]
> 看来您那个给overlay扩容的视频，我的R4s用的外接优盘来扩容的，我发现弄完没问题啊，重启扩容的也还在，但是重新刷完固件（即便我选保留配置）之后这个设为外置的overlay的配置就掉了啊（具体表现为df -h看挂载点和大小，发现恢复回原来内置的overlay了），我尝试了一下，要把优盘上的那些/upper /work/之类全删除再重新拷贝一次，然后再重新挂载重启一次才能好啊，这个就有点烦了，我没几天都要刷一个新版本，这样弄的话，那我每次升级固件不得手工维护得烦死，有什么好办法吗@esirplayground
> 
> 我初步怀疑是刷了固件之后原来在优盘上那些目录里的内容不知什么原因不同步了，或者不相容了，导致mount不上，需要重新同步内置overlay得内容后才能挂载，猜的，不知道是不是这样，因为重新拷贝一下内置overlay得内容后就能挂在上了。

是的，在使用新固件的时候，我也遇见了相同的问题
我都是装在U盘上的，之前是用的是openwrt-gdq-winter[2022]-x86-64-generic-squashfs-legacy.img.gz，安装油管的视频教程可以成功扩容，但是当我用了新固件openwrt-gdq-v2[2023]-x86-64-generic-squashfs-combined.img.gz后，那个教程就失效了，每次重启后df -h发现/dev/sda3没有被挂载。算了，我准备听取esir大佬的意见，自己编译一个overlay大一点的固件。
