### ISSUE TITLE
passwall的延迟正常，可用性测试都是超时，导致节点全都不可用

### ISSUE THREAD

**Issue by cubale** [esirplayground/AutoBuild-OpenWrt#284]
自从esir大大编译的opwnwrt 2022－spring及以后的几个版本，passwall都不能正常工作。机场正常，passwall订阅正常，节点的ping测试正常，但就是可用性测试超时，导致无法连接。请问这是什么原因。而在先前的老版本的passwall没有可用性测试的时候， 却可以正常连接。请问问题出在哪？
![20220911182207](https://user-images.githubusercontent.com/28473776/189522673-d1870a29-9587-4ad0-b3b9-2a322e8746a8.jpg)

**Comment by cubale** [comment]
@esirplayground

**Comment by corepro** [comment]
祝你天天开心

**Comment by cubale** [comment]
> 祝你天天开心

3Q。难道这个问题就无解了吗。就没有其他人遇到吗

**Comment by cubale** [comment]
@Yangmeism 没有解决，我试过别人编译的openwrt版本，里面的passwall也是不能正常连接，应该是新版本都不行了。我后来就放弃了。用openclash可以的，后面都是用的openclash。istoreos里面安装openclash也是可以用的。不用换回pve＋老的op

**Comment by munannan1997** [comment]
我也是用的istoreos系统，装了passwall，节点正常（经过Qx检测），但是passwall里显示节点超时，**最后的解决办法是，在passwall里关闭启用，然后再打开启用，所有的功能又正常了**，目前还没发现这是经常性的故障还是偶发性的故障（刚买R2S几天），等下一次有类似问题再来回复吧。

**Comment by Paulchen0307** [comment]
同一個問題 有辦法解決嗎？

**Comment by esirplayground** [comment]
找作者，事半功倍 https://github.com/xiaorouji/openwrt-passwall

**Comment by shuishuo615** [comment]
同样的问题
